version: "3.0"
services:
  dockerapp:
    image: 176616422154.dkr.ecr.us-west-2.amazonaws.com/circleci-01:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis:3.2.0
